# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "45c0745fb9bb09f8b0317a13948d558a"
name = "php-demo"
handle = "php-demo-4"
application_url = "https://guided-funk-duties-poultry.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extrension-madhavi.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://guided-funk-duties-poultry.trycloudflare.com/auth/callback",
  "https://guided-funk-duties-poultry.trycloudflare.com/auth/shopify/callback",
  "https://guided-funk-duties-poultry.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
